<#
.SYNOPSIS
    Diagnose the Universal Print registration, and optionally print one page.

.DESCRIPTION
    Answers, with evidence rather than inference:

      1. How is this printer registered -- natively (Universal Print ready) or
         through a connector? The Connectors blade being empty is ambiguous on its
         own, because "Last seen" updates from a connector heartbeat too.
      2. What content types does the printer ACTUALLY report to the API? (The
         portal's Properties tab shows the default, not the full capability list.)
      3. Does a job submitted through Graph physically come out of the tray?

    Deliberately standalone: no Function App, no SharePoint, no Entra app
    registration. It signs in with the Microsoft Graph PowerShell first-party
    client via device code, so it isolates "does this printer print?" from every
    other moving part in the pipeline. This is the same path already validated in
    the sibling project's docs/gitignore/printer_MFCL5800DW.txt.

.PARAMETER ShareId
    The printer share id. Defaults to Noble's Brother MFC-L5800DW, registered
    2026-08-31. It replaced the DCP-L2540DW, which was not Universal Print ready.

    NOTE: the MFC-L5800DW reports image/pwg-raster ONLY, so running this script
    WITHOUT -DiagnoseOnly will fail: it uploads a PDF. Printing to this device
    needs the PDF -> PWG-raster conversion.

    Expect this default to go stale. Deleting and re-creating a printer share in
    the portal mints a NEW share id -- it happened on 2026-08-31 -- while the
    printer id and its registration are untouched. Graph answers a retired id
    with 404 "The printer share id ... does not match any registered printers",
    which sounds like the device is gone and is not. Step 1 catches that and
    lists the share ids that really exist, so the fix is a copy and paste.

.PARAMETER DiagnoseOnly
    Run steps 1-4 and stop. Nothing is submitted and nothing prints.

.PARAMETER PdfPath
    A PDF to print. Omit and a small one is generated by scripts/make_test_pdf.py.

.EXAMPLE
    .\scripts\live-printer-check.ps1 -DiagnoseOnly
    .\scripts\live-printer-check.ps1
#>

[CmdletBinding()]
param(
    [string] $ShareId = "4429bf4e-6294-4bcf-bd92-b5f3c3ff47c5",
    [switch] $DiagnoseOnly,
    [string] $PdfPath,
    [int]    $PollSeconds = 120
)

$ErrorActionPreference = "Stop"

function Write-Section($text) {
    Write-Host ""
    Write-Host ("=" * 72) -ForegroundColor DarkGray
    Write-Host $text -ForegroundColor Cyan
    Write-Host ("=" * 72) -ForegroundColor DarkGray
}

function Write-Finding($label, $value, $colour = "Gray") {
    Write-Host ("  {0,-26}: " -f $label) -NoNewline
    Write-Host $value -ForegroundColor $colour
}

function Write-Timestamp($label, $value) {
    # Graph returns these as UTC. Printing the raw value renders it with the
    # local SHORT format while still holding the UTC instant, so a "Last seen"
    # eight hours ahead of Vancouver looks like it is in the future and the
    # printer looks broken. Label the zone and show both.
    if (-not $value) { Write-Finding $label "(none)"; return }
    $utc = [datetime]::Parse($value, [cultureinfo]::InvariantCulture,
                             [System.Globalization.DateTimeStyles]::AdjustToUniversal -bor
                             [System.Globalization.DateTimeStyles]::AssumeUniversal)
    $local = $utc.ToLocalTime()
    Write-Finding $label ("{0:yyyy-MM-dd HH:mm:ss} UTC  ({1:yyyy-MM-dd HH:mm:ss} local)" -f $utc, $local)
}

# --- 0. sign in ---------------------------------------------------------------

Write-Section "0. Sign in"

if (-not (Get-Module -ListAvailable -Name Microsoft.Graph.Authentication)) {
    Write-Host "  Installing Microsoft.Graph.Authentication (current user)..." -ForegroundColor Yellow
    Install-Module Microsoft.Graph.Authentication -Scope CurrentUser -Force -AllowClobber
}
Import-Module Microsoft.Graph.Authentication

# PrintConnector.Read.All is requested ONLY by this diagnostic script, so it can
# answer the registration question. The Function App deliberately does not ask
# for it -- see README, "No connector".
$scopes = @(
    "PrinterShare.ReadBasic.All",
    "Printer.Read.All",
    "PrintConnector.Read.All",
    "PrintJob.ReadWriteBasic"
)

if (-not (Get-MgContext)) {
    Connect-MgGraph -Scopes $scopes -UseDeviceAuthentication
}
$context = Get-MgContext
Write-Finding "Signed in as" $context.Account Green
Write-Finding "Tenant" $context.TenantId

$missing = $scopes | Where-Object { $context.Scopes -notcontains $_ }
if ($missing) {
    Write-Host "  NOTE: these scopes were not granted: $($missing -join ', ')" -ForegroundColor Yellow
    Write-Host "        PrintConnector.Read.All needs admin consent; without it" -ForegroundColor Yellow
    Write-Host "        step 3 cannot run, but printing still can." -ForegroundColor Yellow
}

# --- 1. the share -------------------------------------------------------------

Write-Section "1. Printer share  (what Submit and Poll address)"

try {
    $share = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/print/shares/$ShareId`?`$select=id,displayName,isAcceptingJobs,capabilities,status&`$expand=printer(`$select=id)"
} catch {
    # A 404 here is almost always a STALE SHARE ID, not a missing printer.
    # Deleting and re-creating a printer share in the portal mints a NEW share
    # id; the printer id is untouched. The bare Graph error says "does not match
    # any registered printers", which reads like the device is gone and sends
    # people to the wrong blade. So answer the real question instead: list what
    # the tenant actually has, with the id to copy.
    Write-Host ""
    Write-Host "  The share id $ShareId did not resolve." -ForegroundColor Red
    Write-Host "  $($_.Exception.Message.Split([char]10)[0])" -ForegroundColor DarkGray
    Write-Host ""
    Write-Host "  Shares that DO exist in this tenant:" -ForegroundColor Cyan

    # "no shares" and "could not ask" are different answers and must not print
    # the same line: the first says go and share the printer, the second says
    # nothing at all about whether a share exists.
    $shares = @()
    $listed = $false
    try {
        $shares = @((Invoke-MgGraphRequest -Method GET `
            -Uri "https://graph.microsoft.com/v1.0/print/shares`?`$select=id,displayName,createdDateTime")["value"])
        $listed = $true
    } catch {
        Write-Host "      (could not list them: $($_.Exception.Message.Split([char]10)[0]))" -ForegroundColor Yellow
        Write-Host "       Read the id from Universal Print > Printers > the printer >" -ForegroundColor Yellow
        Write-Host "       Overview > Share Id." -ForegroundColor Yellow
    }

    if ($listed -and -not $shares) {
        Write-Host "      (none -- the printer is registered but not shared. Share it in" -ForegroundColor Yellow
        Write-Host "       Universal Print > Printers > the printer > Share.)" -ForegroundColor Yellow
    }
    foreach ($existing in $shares) {
        Write-Host ("      {0}  {1}" -f $existing["id"], $existing["displayName"])
        if ($existing["createdDateTime"]) {
            Write-Host ("      {0,-36}  shared {1}" -f "", $existing["createdDateTime"]) -ForegroundColor DarkGray
        }
    }

    Write-Host ""
    Write-Host "  Re-run with:  .\scripts\live-printer-check.ps1 -ShareId <id above> -DiagnoseOnly" -ForegroundColor Yellow
    Write-Host "  Then update the default in this script, README.md, the docs, the" -ForegroundColor Yellow
    Write-Host "  test fixture, AND the printerShareId in every Power Automate flow --" -ForegroundColor Yellow
    Write-Host "  a re-share breaks all of them at once." -ForegroundColor Yellow
    throw
}

$printerId = $share["printer"]["id"]
$capabilities = $share["capabilities"]
$contentTypes = @($capabilities["contentTypes"])

Write-Finding "Share id" $share["id"]
Write-Finding "Display name" $share["displayName"]
Write-Finding "Printer id" $printerId Yellow
Write-Finding "Is accepting jobs" $share["isAcceptingJobs"]
Write-Finding "Status" $share["status"]["state"]

Write-Host ""
Write-Host "  Content types the printer REPORTS to the API:" -ForegroundColor Cyan
foreach ($type in $contentTypes) { Write-Host "      $type" }

if ($contentTypes -contains "application/pdf") {
    Write-Host "  => application/pdf is supported: the pipeline can submit SharePoint PDFs as-is." -ForegroundColor Green
} else {
    Write-Host "  => application/pdf is NOT in the list. Submit will fail every file at" -ForegroundColor Red
    Write-Host "     preflight with 'does not accept application/pdf'." -ForegroundColor Red
    if ($contentTypes -contains "image/pwg-raster") {
        Write-Host "     This printer takes image/pwg-raster, so the fix is CLIENT-SIDE:" -ForegroundColor Yellow
        Write-Host "     rasterize the PDF before upload. Universal Print will not do it --" -ForegroundColor Yellow
        Write-Host "     the only conversion it performs is OXPS -> PDF, and only for" -ForegroundColor Yellow
        Write-Host "     printers that already accept PDF." -ForegroundColor Yellow
    } else {
        Write-Host "     No conversion path is known for this capability list, so this" -ForegroundColor Red
        Write-Host "     needs a printer-side fix." -ForegroundColor Red
    }
}

# --- 2. the printer -----------------------------------------------------------

Write-Section "2. Printer  (what cancel addresses)"

$printer = Invoke-MgGraphRequest -Method GET `
    -Uri "https://graph.microsoft.com/v1.0/print/printers/$printerId"

Write-Finding "Model" $printer["model"]
Write-Finding "Manufacturer" $printer["manufacturer"]
Write-Timestamp "Registered" $printer["registeredDateTime"]
Write-Timestamp "Last seen" $printer["lastSeenDateTime"]
Write-Finding "Status" $printer["status"]["state"]

# --- 3. how is it registered? -------------------------------------------------

Write-Section "3. Registration path  (the question the portal left ambiguous)"

$connectorsKnown = $false
try {
    $printerConnectors = @((Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/print/printers/$printerId/connectors")["value"])
    $tenantConnectors = @((Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/print/connectors")["value"])
    $connectorsKnown = $true
} catch {
    Write-Host "  Could not read connectors: $($_.Exception.Message)" -ForegroundColor Yellow
    Write-Host "  (PrintConnector.Read.All is probably not consented.)" -ForegroundColor Yellow
}

if ($connectorsKnown) {
    Write-Finding "Connectors on this printer" $printerConnectors.Count
    Write-Finding "Connectors in the tenant" $tenantConnectors.Count

    foreach ($connector in $printerConnectors) {
        Write-Host ""
        Write-Finding "  connector name" $connector["name"]
        Write-Finding "  host" $connector["fullyQualifiedDomainName"]
        Write-Finding "  OS" $connector["operatingSystem"]
        Write-Finding "  app version" $connector["appVersion"]
    }

    Write-Host ""
    if ($printerConnectors.Count -gt 0) {
        Write-Host "  => CONNECTOR-BACKED. A Windows machine is bridging this printer." -ForegroundColor Green
        Write-Host "     That machine must be powered on and running the connector service" -ForegroundColor Yellow
        Write-Host "     for anything to print. It is a single point of failure worth" -ForegroundColor Yellow
        Write-Host "     knowing about before this goes into production." -ForegroundColor Yellow
    } elseif ($tenantConnectors.Count -gt 0) {
        Write-Host "  => No connector is bound to THIS printer, but the tenant has" -ForegroundColor Yellow
        Write-Host "     $($tenantConnectors.Count). Either this printer registered natively," -ForegroundColor Yellow
        Write-Host "     or its connector binding was lost. Step 5 settles it." -ForegroundColor Yellow
    } else {
        Write-Host "  => No connectors anywhere in the tenant." -ForegroundColor Yellow
        Write-Host "     If this printer still prints, it is Universal Print ready and" -ForegroundColor Yellow
        Write-Host "     registered directly -- the better path, per Microsoft." -ForegroundColor Yellow
        Write-Host "     If it does NOT print, the registration is broken and jobs will" -ForegroundColor Yellow
        Write-Host "     sit in 'pending' forever. Step 5 settles it." -ForegroundColor Yellow
    }
}

if ($DiagnoseOnly) {
    Write-Host ""
    Write-Host "-DiagnoseOnly: stopping before submitting anything." -ForegroundColor Cyan
    Write-Host "Re-run without it to print a test page and settle the registration question."
    return
}

# --- 4. the document ----------------------------------------------------------

Write-Section "4. Test document"

if (-not $PdfPath) {
    # Into TEMP, not the repo. This is a throwaway artifact of a diagnostic run;
    # writing it beside the source leaves an untracked PDF in the working tree
    # that someone eventually commits.
    $PdfPath = Join-Path ([System.IO.Path]::GetTempPath()) "noble-print-test.pdf"
    $python = Join-Path $PWD ".venv\Scripts\python.exe"
    if (-not (Test-Path $python)) { $python = "py" }
    & $python (Join-Path $PSScriptRoot "make_test_pdf.py") $PdfPath | Out-Host
}

$file = Get-Item $PdfPath
Write-Finding "File" $file.Name
Write-Finding "Size" "$($file.Length) bytes"

# --- 5. submit ----------------------------------------------------------------

Write-Section "5. Submit  (the same four calls the Function App makes)"

Write-Host "  [1/4] POST /print/shares/$ShareId/jobs"
$job = Invoke-MgGraphRequest -Method POST `
    -Uri "https://graph.microsoft.com/v1.0/print/shares/$ShareId/jobs" `
    -ContentType "application/json" `
    -Body (@{ configuration = @{ copies = 1 } } | ConvertTo-Json -Depth 5)

$jobId = $job["id"]
$documentId = $job["documents"][0]["id"]
Write-Finding "  job id" $jobId Green
Write-Finding "  document id" $documentId

Write-Host "  [2/4] POST .../documents/$documentId/createUploadSession"
$session = Invoke-MgGraphRequest -Method POST `
    -Uri "https://graph.microsoft.com/v1.0/print/shares/$ShareId/jobs/$jobId/documents/$documentId/createUploadSession" `
    -ContentType "application/json" `
    -Body (@{ properties = @{
        documentName = $file.Name
        contentType  = "application/pdf"
        size         = [int64]$file.Length
    } } | ConvertTo-Json -Depth 5)

$size = [int64]$file.Length
$lastByte = $size - 1

Write-Host "  [3/4] PUT the bytes  (NO Authorization header -- the upload URL carries its own token)"
# -UseBasicParsing is NOT optional. Without it, Windows PowerShell 5.1 hands the
# response to the Internet Explorer engine and stops with an interactive
# "Script Execution Risk ... Do you want to continue?" prompt -- in the middle of
# a PUT, waiting for a keystroke. It is harmless when a human is watching and it
# HANGS FOREVER when one is not. We want the status code, never a parsed DOM.
$upload = Invoke-WebRequest -Method PUT -Uri $session["uploadUrl"] `
    -Headers @{ "Content-Range" = "bytes 0-$lastByte/$size" } `
    -ContentType "application/octet-stream" -InFile $file.FullName `
    -UseBasicParsing
Write-Finding "  upload status" "$($upload.StatusCode)  (201 = complete)" Green

Write-Host "  [4/4] POST .../jobs/$jobId/start"
$started = Invoke-MgGraphRequest -Method POST `
    -Uri "https://graph.microsoft.com/v1.0/print/shares/$ShareId/jobs/$jobId/start"
Write-Finding "  state after start" $started["state"] Green

# --- 6. poll ------------------------------------------------------------------

Write-Section "6. Poll  (exactly what the status endpoint does)"

$deadline = (Get-Date).AddSeconds($PollSeconds)
$state = ""
do {
    Start-Sleep -Seconds 5
    $current = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/print/shares/$ShareId/jobs/$jobId"
    $status = $current["status"]
    $state = [string]$status["state"]
    $detail = (@($status["details"]) -join ", ")
    Write-Host ("  {0}  state={1}  acquired={2}  {3}" -f `
        (Get-Date -Format "HH:mm:ss"), $state, $status["isAcquiredByPrinter"], $detail)
} while ($state -notin @("completed", "canceled", "aborted") -and (Get-Date) -lt $deadline)

Write-Section "Verdict"

switch ($state) {
    "completed" {
        Write-Host "  PRINTED. The registration works end to end." -ForegroundColor Green
        Write-Host "  The pipeline would now write PRINT_COMPLETED and a 'printed on ...' message."
        if ($connectorsKnown -and $printerConnectors.Count -eq 0) {
            Write-Host ""
            Write-Host "  It printed with NO connector, so this printer is Universal Print" -ForegroundColor Green
            Write-Host "  ready and registered directly. That settles the open question." -ForegroundColor Green
        }
    }
    { $_ -in @("canceled", "aborted") } {
        Write-Host "  The job ended as '$state' without printing." -ForegroundColor Red
        Write-Host "  Poll would write PRINT_FAILED and Resubmit would retry after 72h."
    }
    default {
        Write-Host "  Still '$state' after $PollSeconds seconds -- it has NOT printed." -ForegroundColor Red
        Write-Host ""
        Write-Host "  This is the failure mode the connector question was about:" -ForegroundColor Yellow
        Write-Host "  Universal Print accepted the job, but nothing is delivering it to" -ForegroundColor Yellow
        Write-Host "  the device. Check that the connector host is powered on and running" -ForegroundColor Yellow
        Write-Host "  the connector service, or that the printer itself is online." -ForegroundColor Yellow
        Write-Host ""
        Write-Host "  Note for the pipeline: a job stuck like this stays PRINT_PENDING." -ForegroundColor Yellow
        Write-Host "  Poll writes nothing, and Resubmit cancels and retries it after 72h."
    }
}

Write-Host ""
Write-Host "  Job:      https://portal.azure.com/#view/Universal_Print/PrinterMenuBlade/~/PrinterJobs/printerId/$printerId"
Write-Host "  Job id:   $jobId   (per-printer, not globally unique)"
